# Generated by Django 3.0.5 on 2020-11-18 20:39

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('Website', models.TextField()),
                ('Title', models.TextField()),
                ('Authors', models.TextField()),
                ('Publish_Date', models.DateField()),
                ('Article', models.TextField()),
                ('URL', models.TextField()),
            ],
        ),
    ]
