# Generated by Django 3.0.5 on 2020-11-19 14:28

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('articleApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Articleinfo',
            fields=[
                ('id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('Website', models.TextField()),
                ('Title', models.TextField()),
                ('Authors', models.TextField()),
                ('Publish_Date', models.TextField()),
                ('Article', models.TextField()),
                ('URL', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Article',
        ),
    ]
